// Cross-validation tests: compare plapoint output against reference data
// Reference data generated by scipy/numpy (mathematically correct).

#include <gtest/gtest.h>
#include <plapoint/core/point_cloud.h>
#include <plapoint/search/kdtree.h>
#include <plapoint/filters/voxel_grid.h>
#include <plapoint/filters/radius_outlier_removal.h>
#include <plapoint/filters/uniform_downsample.h>
#include <plapoint/features/normal_estimation.h>
#include <plapoint/registration/icp.h>
#include <plapoint/mesh/marching_cubes.h>
#include <plapoint/mesh/poisson_reconstruction.h>
#include <plapoint/io/ply_io.h>
#include <plamatrix/plamatrix.h>

#include <cmath>
#include <cstring>
#include <fstream>
#include <memory>
#include <string>
#include <vector>

// ---- Simple binary reader for reference data ----
struct BinData
{
    std::vector<char> raw;
    int rows = 0, cols = 0;

    static BinData load(const std::string& path)
    {
        std::ifstream f(path, std::ios::binary);
        if (!f) throw std::runtime_error("Cannot open " + path);
        BinData d;
        f.read(reinterpret_cast<char*>(&d.rows), 4);
        f.read(reinterpret_cast<char*>(&d.cols), 4);
        int total = d.rows * d.cols;
        // Determine element size from file extension or path convention
        // We read raw and cast later
        d.raw.resize(static_cast<std::size_t>(total * 4)); // assume float or int32 = 4 bytes
        f.read(d.raw.data(), static_cast<std::streamsize>(d.raw.size()));
        return d;
    }

    const float* asFloat(int i = 0) const { return reinterpret_cast<const float*>(raw.data()) + i * cols; }
    const int*   asInt(int i = 0)   const { return reinterpret_cast<const int*>(raw.data())   + i * cols; }
    const double* asDouble(int i = 0) const
    {
        // double = 8 bytes, need to re-read
        return reinterpret_cast<const double*>(raw.data()) + i * cols;
    }

    static BinData loadDouble(const std::string& path)
    {
        std::ifstream f(path, std::ios::binary);
        if (!f) throw std::runtime_error("Cannot open " + path);
        BinData d;
        f.read(reinterpret_cast<char*>(&d.rows), 4);
        f.read(reinterpret_cast<char*>(&d.cols), 4);
        int total = d.rows * d.cols;
        d.raw.resize(static_cast<std::size_t>(total * 8));
        f.read(d.raw.data(), static_cast<std::streamsize>(d.raw.size()));
        return d;
    }
};

static std::string refPath(const std::string& name)
{
    // Try relative from repo root first, then from build directory
    std::string path = "test/validation/reference_data/" + name;
    std::ifstream test(path);
    if (test.good()) return path;
    return "../" + path;
}

// ---- KdTree KNN Cross-Validation ----
class KdTreeValidation : public ::testing::TestWithParam<int> {};
TEST_P(KdTreeValidation, KnnMatchesScipy)
{
    int k = GetParam();
    using Scalar = float;

    auto pts = BinData::load(refPath("knn_points.bin"));
    auto qrs = BinData::load(refPath("knn_queries.bin"));
    auto ref_idx = BinData::load(refPath("knn_indices_k" + std::to_string(k) + ".bin"));

    int N = pts.rows, M = qrs.rows;

    plamatrix::DenseMatrix<Scalar, plamatrix::Device::CPU> mat(N, 3);
    for (int i = 0; i < N; ++i)
        for (int c = 0; c < 3; ++c)
            mat(i, c) = pts.asFloat(i)[c];

    auto cloud = std::make_shared<plapoint::PointCloud<Scalar, plamatrix::Device::CPU>>(std::move(mat));
    plapoint::search::KdTree<Scalar, plamatrix::Device::CPU> tree;
    tree.setInputCloud(cloud);
    tree.build();

    int errors = 0;
    for (int i = 0; i < M; ++i)
    {
        plamatrix::Vec3<Scalar> q{qrs.asFloat(i)[0], qrs.asFloat(i)[1], qrs.asFloat(i)[2]};
        auto result = tree.nearestKSearch(q, k);
        ASSERT_EQ(static_cast<int>(result.size()), k) << "Query " << i;
        for (int j = 0; j < k; ++j)
        {
            // Allow tied distances to differ in order
        }
        // Check that result contains the same indices as reference (order may differ for ties)
        std::vector<int> ref_vec(ref_idx.asInt(i), ref_idx.asInt(i) + k);
        std::sort(ref_vec.begin(), ref_vec.end());
        std::sort(result.begin(), result.end());
        for (int j = 0; j < k; ++j)
        {
            if (result[static_cast<std::size_t>(j)] != ref_vec[static_cast<std::size_t>(j)])
                ++errors;
        }
    }
    // Allow small number of tie-related differences
    EXPECT_LE(errors, M * k / 10) << errors << " mismatches out of " << (M * k);
}
INSTANTIATE_TEST_SUITE_P(K, KdTreeValidation, ::testing::Values(1, 4, 8, 16));

// ---- VoxelGrid Cross-Validation ----
TEST(VoxelGridValidation, CentroidsMatchReference)
{
    using Scalar = float;
    auto input = BinData::load(refPath("voxelgrid_input.bin"));
    auto ref_centroids = BinData::load(refPath("voxelgrid_centroids.bin"));
    auto leaf_data = BinData::load(refPath("voxelgrid_leaf.bin"));
    Scalar leaf = leaf_data.asFloat()[0];

    plamatrix::DenseMatrix<Scalar, plamatrix::Device::CPU> mat(input.rows, 3);
    for (int i = 0; i < input.rows; ++i)
        for (int c = 0; c < 3; ++c)
            mat(i, c) = input.asFloat(i)[c];

    auto cloud = std::make_shared<plapoint::PointCloud<Scalar, plamatrix::Device::CPU>>(std::move(mat));
    plapoint::VoxelGrid<Scalar, plamatrix::Device::CPU> vg;
    vg.setInputCloud(cloud);
    vg.setLeafSize(leaf, leaf, leaf);

    plapoint::PointCloud<Scalar, plamatrix::Device::CPU> output;
    vg.filter(output);

    // Same voxel count?
    EXPECT_EQ(static_cast<int>(output.size()), ref_centroids.rows);

    // Compare centroids (voxel order may differ, so check each centroid exists in reference)
    Scalar max_dist = 0;
    for (int i = 0; i < static_cast<int>(output.size()); ++i)
    {
        Scalar ox = output.points().getValue(i, 0);
        Scalar oy = output.points().getValue(i, 1);
        Scalar oz = output.points().getValue(i, 2);

        // Find closest reference centroid
        Scalar best = 1e10;
        for (int j = 0; j < ref_centroids.rows; ++j)
        {
            Scalar dx = ox - ref_centroids.asFloat(j)[0];
            Scalar dy = oy - ref_centroids.asFloat(j)[1];
            Scalar dz = oz - ref_centroids.asFloat(j)[2];
            Scalar d = dx*dx + dy*dy + dz*dz;
            if (d < best) best = d;
        }
        max_dist = std::max(max_dist, std::sqrt(best));
        EXPECT_LT(std::sqrt(best), Scalar(leaf * 1.5)) << "Centroid " << i << " too far from reference";
    }
}

// ---- NormalEstimation Cross-Validation ----
TEST(NormalEstimationValidation, SphereNormals)
{
    using Scalar = float;
    auto input = BinData::load(refPath("normal_est_input.bin"));
    auto ref_normals = BinData::load(refPath("normal_est_normals.bin"));
    auto k_data = BinData::load(refPath("normal_est_k.bin"));
    int K = k_data.asInt()[0];

    int N = input.rows;
    plamatrix::DenseMatrix<Scalar, plamatrix::Device::CPU> mat(N, 3);
    for (int i = 0; i < N; ++i)
        for (int c = 0; c < 3; ++c)
            mat(i, c) = input.asFloat(i)[c];

    auto cloud = std::make_shared<plapoint::PointCloud<Scalar, plamatrix::Device::CPU>>(std::move(mat));

    auto tree = std::make_shared<plapoint::search::KdTree<Scalar, plamatrix::Device::CPU>>();
    tree->setInputCloud(cloud);
    tree->build();

    plapoint::NormalEstimation<Scalar, plamatrix::Device::CPU> ne;
    ne.setInputCloud(cloud);
    ne.setSearchMethod(tree);
    ne.setKSearch(K);
    auto normals = ne.compute();

    // Compare normals (allow sign flip since orientation is ambiguous)
    Scalar avg_angle = 0;
    for (int i = 0; i < N; ++i)
    {
        Scalar nx = normals.getValue(i, 0);
        Scalar ny = normals.getValue(i, 1);
        Scalar nz = normals.getValue(i, 2);

        Scalar rx = ref_normals.asFloat(i)[0];
        Scalar ry = ref_normals.asFloat(i)[1];
        Scalar rz = ref_normals.asFloat(i)[2];

        Scalar dot = nx*rx + ny*ry + nz*rz;
        // Accept either direction
        Scalar angle = std::acos(std::min(Scalar(1), std::abs(dot)));
        avg_angle += angle;
    }
    avg_angle /= Scalar(N);
    EXPECT_LT(avg_angle, Scalar(0.2)) << "Average angular error: " << avg_angle << " rad";
}

// ---- ICP Cross-Validation ----
TEST(ICPValidation, RecoversKnownTransform)
{
    using Scalar = float;
    auto src_data = BinData::loadDouble(refPath("icp_source.bin"));
    auto tgt_data = BinData::loadDouble(refPath("icp_target.bin"));
    auto R_data   = BinData::loadDouble(refPath("icp_R.bin"));
    auto t_data   = BinData::loadDouble(refPath("icp_t.bin"));

    int N = src_data.rows;

    // Build source and target clouds
    plamatrix::DenseMatrix<Scalar, plamatrix::Device::CPU> src_mat(N, 3);
    plamatrix::DenseMatrix<Scalar, plamatrix::Device::CPU> tgt_mat(N, 3);
    for (int i = 0; i < N; ++i)
        for (int c = 0; c < 3; ++c)
        {
            src_mat(i, c) = static_cast<Scalar>(src_data.asDouble(i)[c]);
            tgt_mat(i, c) = static_cast<Scalar>(tgt_data.asDouble(i)[c]);
        }

    auto source = std::make_shared<plapoint::PointCloud<Scalar, plamatrix::Device::CPU>>(std::move(src_mat));
    auto target = std::make_shared<plapoint::PointCloud<Scalar, plamatrix::Device::CPU>>(std::move(tgt_mat));

    plapoint::IterativeClosestPoint<Scalar, plamatrix::Device::CPU> icp;
    icp.setInputSource(source);
    icp.setInputTarget(target);
    icp.setMaxIterations(50);

    plapoint::PointCloud<Scalar, plamatrix::Device::CPU> output;
    icp.align(output);

    EXPECT_TRUE(icp.hasConverged());

    const auto& T = icp.getFinalTransformation();
    // Check that recovered rotation matches ground truth
    Scalar rot_error = 0;
    for (int i = 0; i < 3; ++i)
        for (int j = 0; j < 3; ++j)
            rot_error += std::abs(T.getValue(i, j) - static_cast<Scalar>(R_data.asDouble()[i*3+j]));
    EXPECT_LT(rot_error, Scalar(0.3)) << "Rotation error: " << rot_error;

    // Check translation
    Scalar t_error = std::abs(T.getValue(0, 3) - static_cast<Scalar>(t_data.asDouble()[0]))
                   + std::abs(T.getValue(1, 3) - static_cast<Scalar>(t_data.asDouble()[1]))
                   + std::abs(T.getValue(2, 3) - static_cast<Scalar>(t_data.asDouble()[2]));
    EXPECT_LT(t_error, Scalar(0.3)) << "Translation error: " << t_error;
}

// ---- MarchingCubes Cross-Validation ----
TEST(MarchingCubesValidation, SphereVerticesOnSurface)
{
    using Scalar = float;
    auto r_data = BinData::load(refPath("mc_sphere_r.bin"));
    Scalar R = r_data.asFloat()[0];

    auto sphere_fn = [R](Scalar x, Scalar y, Scalar z) {
        return x*x + y*y + z*z - R*R;
    };

    plapoint::mesh::MarchingCubes<Scalar> mc;
    mc.setBounds({-3,-3,-3}, {3,3,3});
    mc.setResolution(30, 30, 30);
    mc.setIsoLevel(Scalar(0));

    auto [verts, faces] = mc.extract(sphere_fn);

    EXPECT_GT(verts.rows(), 100) << "Too few vertices for sphere";

    Scalar max_error = 0;
    int outside = 0;
    for (plamatrix::Index i = 0; i < verts.rows(); ++i)
    {
        Scalar x = verts.getValue(i, 0);
        Scalar y = verts.getValue(i, 1);
        Scalar z = verts.getValue(i, 2);
        Scalar r2 = x*x + y*y + z*z;
        Scalar err = std::abs(std::sqrt(r2) - R);
        max_error = std::max(max_error, err);
        if (err > Scalar(0.5)) ++outside;
    }
    EXPECT_LT(max_error, Scalar(0.5)) << "Max vertex distance from sphere surface: " << max_error;
    EXPECT_LT(outside, verts.rows() / 10) << outside << " vertices too far from surface";
}

// ---- RadiusOutlierRemoval Cross-Validation ----
TEST(RadiusOutlierRemovalValidation, MatchesScipy)
{
    using Scalar = float;
    auto input = BinData::load(refPath("radius_filter_input.bin"));
    auto ref_mask = BinData::load(refPath("radius_filter_inliers.bin"));

    int N = input.rows;
    plamatrix::DenseMatrix<Scalar, plamatrix::Device::CPU> mat(N, 3);
    for (int i = 0; i < N; ++i)
        for (int c = 0; c < 3; ++c)
            mat(i, c) = input.asFloat(i)[c];

    auto cloud = std::make_shared<plapoint::PointCloud<Scalar, plamatrix::Device::CPU>>(std::move(mat));

    plapoint::RadiusOutlierRemoval<Scalar, plamatrix::Device::CPU> ror;
    ror.setInputCloud(cloud);
    ror.setRadius(Scalar(1.0));
    ror.setMinNeighbors(5);

    plapoint::PointCloud<Scalar, plamatrix::Device::CPU> output;
    ror.filter(output);

    // Count expected inliers
    int expected_inliers = 0;
    for (int i = 0; i < N; ++i)
        if (ref_mask.asInt()[i])
            ++expected_inliers;

    // Relaxed check: plapoint uses KdTree, scipy uses ball query — results should be very close
    EXPECT_GE(static_cast<int>(output.size()), expected_inliers * 0.9);
    EXPECT_LE(static_cast<int>(output.size()), expected_inliers * 1.1);
}

// ---- UniformDownsample Cross-Validation ----
TEST(UniformDownsampleValidation, MatchesReference)
{
    using Scalar = float;
    auto input = BinData::load(refPath("uniform_down_input.bin"));
    auto ref_out = BinData::load(refPath("uniform_down_output.bin"));
    auto step_data = BinData::load(refPath("uniform_down_step.bin"));
    int step = step_data.asInt()[0];

    int N = input.rows;
    plamatrix::DenseMatrix<Scalar, plamatrix::Device::CPU> mat(N, 3);
    for (int i = 0; i < N; ++i)
        for (int c = 0; c < 3; ++c)
            mat(i, c) = input.asFloat(i)[c];

    auto cloud = std::make_shared<plapoint::PointCloud<Scalar, plamatrix::Device::CPU>>(std::move(mat));

    plapoint::UniformDownsample<Scalar, plamatrix::Device::CPU> ud;
    ud.setInputCloud(cloud);
    ud.setStep(step);

    plapoint::PointCloud<Scalar, plamatrix::Device::CPU> output;
    ud.filter(output);

    EXPECT_EQ(static_cast<int>(output.size()), ref_out.rows);
    for (int i = 0; i < ref_out.rows; ++i)
        for (int c = 0; c < 3; ++c)
            EXPECT_FLOAT_EQ(output.points().getValue(i, c), ref_out.asFloat(i)[c])
                << "Mismatch at point " << i << " dim " << c;
}

// ---- PoissonReconstruction validation ----
TEST(PoissonValidation, ReconstructsMeshFromSphere)
{
    using Scalar = float;
    auto cloud = plapoint::io::readPly<Scalar>(refPath("poisson_input.ply"));

    plapoint::mesh::PoissonReconstruction<Scalar> pr;
    pr.setInputCloud(cloud);
    pr.setDepth(5);
    pr.setSolverIterations(30);

    auto [verts, faces] = pr.reconstruct();
    EXPECT_GT(verts.rows(), 0);
    EXPECT_GT(faces.rows(), 0);
}
